language: ruby
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install bundler
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database todo_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec --format doc
